# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDelievery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='services.Service')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('dish', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='services.Service')),
                ('beg_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='services.Service')),
                ('document', models.FileField(upload_to='documents/')),
                ('printer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
