# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20161017_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='document',
            field=models.FileField(upload_to=services.models.Print.document_path),
        ),
    ]
