# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('entry', models.TextField(verbose_name='Content')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Pubication time')),
                ('upd_time', models.DateTimeField(auto_now_add=True, verbose_name='Last update')),
                ('author', models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
