# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20161026_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('entry', models.TextField(verbose_name='Content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='feed.Post')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Pubication time')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
    ]
