# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 23:54
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20161031_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=redactor.fields.RedactorField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='entry',
            field=redactor.fields.RedactorField(verbose_name='Текст поста'),
        ),
    ]
