# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 03:47
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161016_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.User.user_avatars_path, verbose_name='Avatar'),
        ),
    ]
