# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20161026_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultygroup',
            name='group_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
