# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('groups', '0003_auto_20161031_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultygroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='library.Subject', verbose_name='Предметы'),
        ),
    ]
