# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 03:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('lesson_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('lesson_title', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.FacultyGroup')),
            ],
        ),
    ]
