# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0005_auto_20161026_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.FacultyGroup'),
        ),
    ]
