# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0006_auto_20161026_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='day_of_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.FacultyGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='lesson_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='lesson_title',
            field=models.CharField(max_length=50, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='room',
            field=models.CharField(max_length=10, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='teacher',
            field=models.CharField(max_length=50, verbose_name='Преподаватель'),
        ),
    ]
