# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0007_auto_20161101_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='lesson_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='teacher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Преподаватель'),
        ),
    ]
