# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_auto_20161102_0248'),
        ('groups', '0005_auto_20161102_0248'),
        ('shedule', '0009_auto_20161102_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=2, verbose_name='День недели')),
                ('time_interval', models.IntegerField(choices=[(1, '9:00 - 10:25'), (2, '10:45 - 12:10'), (3, '12:20 - 13:45'), (4, '13:55 - 15:20'), (5, '15:30 - 16:55'), (6, '17:05 - 18:30'), (7, '18:30 - 19:50')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.FacultyGroup', verbose_name='Группа')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Auditory', verbose_name='Аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Teacher', verbose_name='Преподаватель'),
        ),
    ]
