# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0010_auto_20161102_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shedule.Auditory', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shedule.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_interval',
            field=models.IntegerField(choices=[(0, 'Неизвестно'), (1, '9:00 - 10:25'), (2, '10:45 - 12:10'), (3, '12:20 - 13:45'), (4, '13:55 - 15:20'), (5, '15:30 - 16:55'), (6, '17:05 - 18:30'), (7, '18:30 - 19:50')], default=0),
        ),
    ]
