# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0013_auto_20161112_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_interval',
            field=models.IntegerField(choices=[(0, 'Неизвестно'), (1, '9:00 - 10:25'), (2, '10:45 - 12:10'), (3, '12:20 - 13:45'), (4, '13:55 - 15:20'), (5, '15:30 - 16:55'), (6, '17:05 - 18:30'), (7, '18:30 - 19:50')], default=0, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1, verbose_name='День недели'),
        ),
    ]
