# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0014_auto_20161129_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=2, verbose_name='День недели'),
        ),
    ]
